<a href="https://colab.research.google.com/github/Awoyawson/Artificial-Neutral-Network/blob/main/ANNLAB1_(RegressionHousing).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preparation

In [22]:
 import pandas as pd

In [23]:
# we imported a data: Selling price of a given house in the Boston(MA) Area
from sklearn.datasets import load_boston
# we rename our dataset to boston_dataset
boston_dataset = load_boston()
boston_dataset
#boston_dataset.features
# we use the format to choose the dataset we want to use

{'DESCR': ".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n        - PTRATIO  pupil-teacher ratio by town\n        - B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\n        - LSTAT    % lower status of the population\n        - MEDV     Median value of owner-occupied homes in $1000's\n\n    :Missing Attribute Values: None\n\n    :Creator: Harrison, D. and Rubinfeld, D.L.\n\nThis is a copy of UCI ML housing dataset.\nhttps://archive.ics.uci.edu/ml/machine-learning-databases/housing/\n\n\nThis dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.\n\nThe Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic\nprices and the demand for clean air', J. Environ. Economics & Management,\nvol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics\n...', Wiley, 1980.   N.B. Various transformations are used in the table on\npages 244-261 of the latter.\n\nThe Boston house-price data has been used in many machine learning papers that address regression\nproblems.   \n     \n.. topic:: References\n\n   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.\n   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.\n",
 'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'feature_names': array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
        'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7'),
 'filename': '/usr/local/lib/python3.7/dist-packages/sklearn/datasets/data/boston_house_prices.csv',
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
        19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
        20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
        23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
        33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
        21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
        20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
        23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
        15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21.5, 19.6, 15.3, 19.4,
        17. , 15.6, 13.1, 41.3, 24.3, 23.3, 27. , 50. , 50. , 50. , 22.7,
        25. , 50. , 23.8, 23.8, 22.3, 17.4, 19.1, 23.1, 23.6, 22.6, 29.4,
        23.2, 24.6, 29.9, 37.2, 39.8, 36.2, 37.9, 32.5, 26.4, 29.6, 50. ,
        32. , 29.8, 34.9, 37. , 30.5, 36.4, 31.1, 29.1, 50. , 33.3, 30.3,
        34.6, 34.9, 32.9, 24.1, 42.3, 48.5, 50. , 22.6, 24.4, 22.5, 24.4,
        20. , 21.7, 19.3, 22.4, 28.1, 23.7, 25. , 23.3, 28.7, 21.5, 23. ,
        26.7, 21.7, 27.5, 30.1, 44.8, 50. , 37.6, 31.6, 46.7, 31.5, 24.3,
        31.7, 41.7, 48.3, 29. , 24. , 25.1, 31.5, 23.7, 23.3, 22. , 20.1,
        22.2, 23.7, 17.6, 18.5, 24.3, 20.5, 24.5, 26.2, 24.4, 24.8, 29.6,
        42.8, 21.9, 20.9, 44. , 50. , 36. , 30.1, 33.8, 43.1, 48.8, 31. ,
        36.5, 22.8, 30.7, 50. , 43.5, 20.7, 21.1, 25.2, 24.4, 35.2, 32.4,
        32. , 33.2, 33.1, 29.1, 35.1, 45.4, 35.4, 46. , 50. , 32.2, 22. ,
        20.1, 23.2, 22.3, 24.8, 28.5, 37.3, 27.9, 23.9, 21.7, 28.6, 27.1,
        20.3, 22.5, 29. , 24.8, 22. , 26.4, 33.1, 36.1, 28.4, 33.4, 28.2,
        22.8, 20.3, 16.1, 22.1, 19.4, 21.6, 23.8, 16.2, 17.8, 19.8, 23.1,
        21. , 23.8, 23.1, 20.4, 18.5, 25. , 24.6, 23. , 22.2, 19.3, 22.6,
        19.8, 17.1, 19.4, 22.2, 20.7, 21.1, 19.5, 18.5, 20.6, 19. , 18.7,
        32.7, 16.5, 23.9, 31.2, 17.5, 17.2, 23.1, 24.5, 26.6, 22.9, 24.1,
        18.6, 30.1, 18.2, 20.6, 17.8, 21.7, 22.7, 22.6, 25. , 19.9, 20.8,
        16.8, 21.9, 27.5, 21.9, 23.1, 50. , 50. , 50. , 50. , 50. , 13.8,
        13.8, 15. , 13.9, 13.3, 13.1, 10.2, 10.4, 10.9, 11.3, 12.3,  8.8,
         7.2, 10.5,  7.4, 10.2, 11.5, 15.1, 23.2,  9.7, 13.8, 12.7, 13.1,
        12.5,  8.5,  5. ,  6.3,  5.6,  7.2, 12.1,  8.3,  8.5,  5. , 11.9,
        27.9, 17.2, 27.5, 15. , 17.2, 17.9, 16.3,  7. ,  7.2,  7.5, 10.4,
         8.8,  8.4, 16.7, 14.2, 20.8, 13.4, 11.7,  8.3, 10.2, 10.9, 11. ,
         9.5, 14.5, 14.1, 16.1, 14.3, 11.7, 13.4,  9.6,  8.7,  8.4, 12.8,
        10.5, 17.1, 18.4, 15.4, 10.8, 11.8, 14.9, 12.6, 14.1, 13. , 13.4,
        15.2, 16.1, 17.8, 14.9, 14.1, 12.7, 13.5, 14.9, 20. , 16.4, 17.7,
        19.5, 20.2, 21.4, 19.9, 19. , 19.1, 19.1, 20.1, 19.9, 19.6, 23.2,
        29.8, 13.8, 13.3, 16.7, 12. , 14.6, 21.4, 23. , 23.7, 25. , 21.8,
        20.6, 21.2, 19.1, 20.6, 15.2,  7. ,  8.1, 13.6, 20.1, 21.8, 24.5,
        23.1, 19.7, 18.3, 21.2, 17.5, 16.8, 22.4, 20.6, 23.9, 22. , 11.9])}

In [24]:
#print the data row input  values.
print('data is :{}'.format(boston_dataset.data))

data is :[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]

In [25]:
#print the independent variable in names ,the string names of the variables.
print('indpendent variable names are:{}'.format(boston_dataset.feature_names))

indpendent variable names are:['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']

In [26]:
# print the dependent  value(The response variable)
print('labels or price:{}'.format(boston_dataset.target))

labels or price:[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 30.3 34.6 34.9 32.9 24.1 42.3 48.5 50.  22.6 24.4 22.5 24.4 20.
 21.7 19.3 22.4 28.1 23.7 25.  23.3 28.7 21.5 23.  26.7 21.7 27.5 30.1
 44.8 50.  37.6 31.6 46.7 31.5 24.3 31.7 41.7 48.3 29.  24.  25.1 31.5
 23.7 23.3 22.  20.1 22.2 23.7 17.6 18.5 24.3 20.5 24.5 26.2 24.4 24.8
 29.6 42.8 21.9 20.9 44.  50.  36.  30.1 33.8 43.1 48.8 31.  36.5 22.8
 30.7 50.  43.5 20.7 21.1 25.2 24.4 35.2 32.4 32.  33.2 33.1 29.1 35.1
 45.4 35.4 46.  50.  32.2 22.  20.1 23.2 22.3 24.8 28.5 37.3 27.9 23.9
 21.7 28.6 27.1 20.3 22.5 29.  24.8 22.  26.4 33.1 36.1 28.4 33.4 28.2
 22.8 20.3 16.1 22.1 19.4 21.6 23.8 16.2 17.8 19.8 23.1 21.  23.8 23.1
 20.4 18.5 25.  24.6 23.  22.2 19.3 22.6 19.8 17.1 19.4 22.2 20.7 21.1
 19.5 18.5 20.6 19.  18.7 32.7 16.5 23.9 31.2 17.5 17.2 23.1 24.5 26.6
 22.9 24.1 18.6 30.1 18.2 20.6 17.8 21.7 22.7 22.6 25.  19.9 20.8 16.8
 21.9 27.5 21.9 23.1 50.  50.  50.  50.  50.  13.8 13.8 15.  13.9 13.3
 13.1 10.2 10.4 10.9 11.3 12.3  8.8  7.2 10.5  7.4 10.2 11.5 15.1 23.2
  9.7 13.8 12.7 13.1 12.5  8.5  5.   6.3  5.6  7.2 12.1  8.3  8.5  5.
 11.9 27.9 17.2 27.5 15.  17.2 17.9 16.3  7.   7.2  7.5 10.4  8.8  8.4
 16.7 14.2 20.8 13.4 11.7  8.3 10.2 10.9 11.   9.5 14.5 14.1 16.1 14.3
 11.7 13.4  9.6  8.7  8.4 12.8 10.5 17.1 18.4 15.4 10.8 11.8 14.9 12.6
 14.1 13.  13.4 15.2 16.1 17.8 14.9 14.1 12.7 13.5 14.9 20.  16.4 17.7
 19.5 20.2 21.4 19.9 19.  19.1 19.1 20.1 19.9 19.6 23.2 29.8 13.8 13.3
 16.7 12.  14.6 21.4 23.  23.7 25.  21.8 20.6 21.2 19.1 20.6 15.2  7.
  8.1 13.6 20.1 21.8 24.5 23.1 19.7 18.3 21.2 17.5 16.8 22.4 20.6 23.9
 22.  11.9]

In [27]:
# puting your data in dataframe (in a table form): Panda helps u virsualize data more friendly way
df = pd.DataFrame(boston_dataset.data,columns = boston_dataset.feature_names)
# we create a new  column and  named  price and assign to target
df['Price'] = boston_dataset.target
# showing be the fist 10 datasets
df.head(n=10)

      CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  Price
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33   36.2
5  0.02985   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.12   5.21   28.7
6  0.08829  12.5   7.87   0.0  0.524  ...  311.0     15.2  395.60  12.43   22.9
7  0.14455  12.5   7.87   0.0  0.524  ...  311.0     15.2  396.90  19.15   27.1
8  0.21124  12.5   7.87   0.0  0.524  ...  311.0     15.2  386.63  29.93   16.5
9  0.17004  12.5   7.87   0.0  0.524  ...  311.0     15.2  386.71  17.10   18.9

[10 rows x 14 columns]

In [11]:
# Use the describe () method to understand the data.Helps to find if there is missing data.
df.describe(include ='all')

             CRIM          ZN       INDUS  ...           B       LSTAT       Price
count  506.000000  506.000000  506.000000  ...  506.000000  506.000000  506.000000
mean     3.613524   11.363636   11.136779  ...  356.674032   12.653063   22.532806
std      8.601545   23.322453    6.860353  ...   91.294864    7.141062    9.197104
min      0.006320    0.000000    0.460000  ...    0.320000    1.730000    5.000000
25%      0.082045    0.000000    5.190000  ...  375.377500    6.950000   17.025000
50%      0.256510    0.000000    9.690000  ...  391.440000   11.360000   21.200000
75%      3.677083   12.500000   18.100000  ...  396.225000   16.955000   25.000000
max     88.976200  100.000000   27.740000  ...  396.900000   37.970000   50.000000

[8 rows x 14 columns]

In [32]:
#Create train and test databases
# this library helps you split your Data set.
from sklearn.model_selection import train_test_split
# we extract all the columns who does not have the name price
X = df.loc[:, df.columns != 'Price']
# we extract all the  column with the  name price
y = df.loc[:, df.columns == 'Price']
# random_state is similar to setting a setting a  seed in R
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=123)



When you standardize the whole dataset , it means that you are influencing the validation set with information from your learning data.
Hence, usually we use the mean and the standard deviation on the training data 
set to do standardization.

In [33]:
#Standardization
mean = X_train.mean(axis=0)
std = X_train.std(axis=0)
X_train = (X_train - mean) / std
X_test = (X_test - mean) / std

# Model  Building

Architure based on two Densed layers. the first with 128 and the second with 64 neurons ,both using a ReLU(Rectified Linear UNit) activation function. A dense layer with a linear activation will be used as output layer.

Note: Since it a regression problem:  we need one output layer so only one node that is price
Steps: 
1. First import all the libararies you need 
2. You create an architure for your model

In [29]:
#import libarires 
from keras.models import Sequential
#'Dense' refers to a fully-connected layer
from keras.layers import Dense
#  creating the architure
#The Sequential model is the simplest model type --> a linear stack of layers
model = Sequential()
# To stack the layers, we use the add() method
# input_shape is mandotory for the first layer. the independent variable
#It means 13 input parameters, with 128 neurons in the FIRST hidden layer.
model.add(Dense(128, input_shape=(13,), activation ='relu', name ='dense_layer_1'))
model.add(Dense(64, activation ='relu', name ='dense_layer_2'))
model.add(Dense(1,  activation = 'linear', name ='dense_output'))
# Adding optimizer  and loss function 
#The compile() method allows us to configure the learning further
model.compile(optimizer='adam',loss='mse')
# if you are able to get a summary then you dont have bugs
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_layer_1 (Dense)        (None, 128)               1792
_________________________________________________________________
dense_layer_2 (Dense)        (None, 64)                8256
_________________________________________________________________
dense_output (Dense)         (None, 1)                 65
=================================================================
Total params: 10,113
Trainable params: 10,113
Non-trainable params: 0
_________________________________________________________________

In [30]:
# Now we Train our model:  fit our model using the train data
#
model.fit(X_train, y_train,epochs=100)

Epoch 1/100
12/12 [==============================] - 0s 2ms/step - loss: 562.3365
Epoch 2/100
12/12 [==============================] - 0s 2ms/step - loss: 553.9684
Epoch 3/100
12/12 [==============================] - 0s 2ms/step - loss: 480.2344
Epoch 4/100
12/12 [==============================] - 0s 2ms/step - loss: 348.4762
Epoch 5/100
12/12 [==============================] - 0s 2ms/step - loss: 223.1511
Epoch 6/100
12/12 [==============================] - 0s 2ms/step - loss: 130.6126
Epoch 7/100
12/12 [==============================] - 0s 2ms/step - loss: 77.7466
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 43.0913
Epoch 9/100
12/12 [==============================] - 0s 2ms/step - loss: 37.0846
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 25.8842
Epoch 11/100
12/12 [==============================] - 0s 2ms/step - loss: 21.5377
Epoch 12/100
12/12 [==============================] - 0s 2ms/step - loss: 20.8078
Epoch 13/100
12/12 [==============================] - 0s 2ms/step - loss: 16.7493
Epoch 14/100
12/12 [==============================] - 0s 2ms/step - loss: 24.0278
Epoch 15/100
12/12 [==============================] - 0s 2ms/step - loss: 19.7615
Epoch 16/100
12/12 [==============================] - 0s 2ms/step - loss: 21.0188
Epoch 17/100
12/12 [==============================] - 0s 2ms/step - loss: 16.2744
Epoch 18/100
12/12 [==============================] - 0s 2ms/step - loss: 19.0361
Epoch 19/100
12/12 [==============================] - 0s 2ms/step - loss: 17.0381
Epoch 20/100
12/12 [==============================] - 0s 2ms/step - loss: 14.1922
Epoch 21/100
12/12 [==============================] - 0s 2ms/step - loss: 13.8680
Epoch 22/100
12/12 [==============================] - 0s 2ms/step - loss: 14.8558
Epoch 23/100
12/12 [==============================] - 0s 2ms/step - loss: 13.2956
Epoch 24/100
12/12 [==============================] - 0s 2ms/step - loss: 14.5029
Epoch 25/100
12/12 [==============================] - 0s 2ms/step - loss: 11.9289
Epoch 26/100
12/12 [==============================] - 0s 2ms/step - loss: 16.7313
Epoch 27/100
12/12 [==============================] - 0s 2ms/step - loss: 13.9913
Epoch 28/100
12/12 [==============================] - 0s 2ms/step - loss: 13.2215
Epoch 29/100
12/12 [==============================] - 0s 2ms/step - loss: 14.6014
Epoch 30/100
12/12 [==============================] - 0s 2ms/step - loss: 10.6183
Epoch 31/100
12/12 [==============================] - 0s 2ms/step - loss: 10.8873
Epoch 32/100
12/12 [==============================] - 0s 2ms/step - loss: 9.4582
Epoch 33/100
12/12 [==============================] - 0s 2ms/step - loss: 12.2001
Epoch 34/100
12/12 [==============================] - 0s 2ms/step - loss: 10.8160
Epoch 35/100
12/12 [==============================] - 0s 2ms/step - loss: 10.0438
Epoch 36/100
12/12 [==============================] - 0s 2ms/step - loss: 11.5601
Epoch 37/100
12/12 [==============================] - 0s 2ms/step - loss: 13.0866
Epoch 38/100
12/12 [==============================] - 0s 2ms/step - loss: 8.9093
Epoch 39/100
12/12 [==============================] - 0s 2ms/step - loss: 12.2485
Epoch 40/100
12/12 [==============================] - 0s 2ms/step - loss: 8.9348
Epoch 41/100
12/12 [==============================] - 0s 2ms/step - loss: 10.3865
Epoch 42/100
12/12 [==============================] - 0s 2ms/step - loss: 8.7005
Epoch 43/100
12/12 [==============================] - 0s 2ms/step - loss: 9.7784
Epoch 44/100
12/12 [==============================] - 0s 2ms/step - loss: 12.0350
Epoch 45/100
12/12 [==============================] - 0s 2ms/step - loss: 9.7168
Epoch 46/100
12/12 [==============================] - 0s 2ms/step - loss: 8.4276
Epoch 47/100
12/12 [==============================] - 0s 2ms/step - loss: 11.5733
Epoch 48/100
12/12 [==============================] - 0s 2ms/step - loss: 7.6915
Epoch 49/100
12/12 [==============================] - 0s 2ms/step - loss: 8.7438
Epoch 50/100
12/12 [==============================] - 0s 2ms/step - loss: 9.1606
Epoch 51/100
12/12 [==============================] - 0s 2ms/step - loss: 9.1148
Epoch 52/100
12/12 [==============================] - 0s 3ms/step - loss: 7.4769
Epoch 53/100
12/12 [==============================] - 0s 2ms/step - loss: 10.2669
Epoch 54/100
12/12 [==============================] - 0s 2ms/step - loss: 8.7605
Epoch 55/100
12/12 [==============================] - 0s 2ms/step - loss: 9.4401
Epoch 56/100
12/12 [==============================] - 0s 2ms/step - loss: 8.5443
Epoch 57/100
12/12 [==============================] - 0s 2ms/step - loss: 7.3210
Epoch 58/100
12/12 [==============================] - 0s 2ms/step - loss: 7.2015
Epoch 59/100
12/12 [==============================] - 0s 2ms/step - loss: 7.5430
Epoch 60/100
12/12 [==============================] - 0s 2ms/step - loss: 7.9953
Epoch 61/100
12/12 [==============================] - 0s 2ms/step - loss: 9.1450
Epoch 62/100
12/12 [==============================] - 0s 2ms/step - loss: 8.8880
Epoch 63/100
12/12 [==============================] - 0s 2ms/step - loss: 8.5864
Epoch 64/100
12/12 [==============================] - 0s 2ms/step - loss: 7.2012
Epoch 65/100
12/12 [==============================] - 0s 2ms/step - loss: 7.7720
Epoch 66/100
12/12 [==============================] - 0s 2ms/step - loss: 11.6181
Epoch 67/100
12/12 [==============================] - 0s 2ms/step - loss: 9.1598
Epoch 68/100
12/12 [==============================] - 0s 2ms/step - loss: 10.8948
Epoch 69/100
12/12 [==============================] - 0s 2ms/step - loss: 8.4472
Epoch 70/100
12/12 [==============================] - 0s 2ms/step - loss: 7.9467
Epoch 71/100
12/12 [==============================] - 0s 2ms/step - loss: 7.8170
Epoch 72/100
12/12 [==============================] - 0s 2ms/step - loss: 7.1112
Epoch 73/100
12/12 [==============================] - 0s 2ms/step - loss: 9.8798
Epoch 74/100
12/12 [==============================] - 0s 2ms/step - loss: 7.1797
Epoch 75/100
12/12 [==============================] - 0s 2ms/step - loss: 8.3872
Epoch 76/100
12/12 [==============================] - 0s 2ms/step - loss: 8.1427
Epoch 77/100
12/12 [==============================] - 0s 2ms/step - loss: 6.3179
Epoch 78/100
12/12 [==============================] - 0s 2ms/step - loss: 7.4704
Epoch 79/100
12/12 [==============================] - 0s 2ms/step - loss: 7.2163
Epoch 80/100
12/12 [==============================] - 0s 2ms/step - loss: 8.0420
Epoch 81/100
12/12 [==============================] - 0s 2ms/step - loss: 7.2432
Epoch 82/100
12/12 [==============================] - 0s 2ms/step - loss: 8.3718
Epoch 83/100
12/12 [==============================] - 0s 2ms/step - loss: 6.2945
Epoch 84/100
12/12 [==============================] - 0s 2ms/step - loss: 7.3794
Epoch 85/100
12/12 [==============================] - 0s 2ms/step - loss: 7.4186
Epoch 86/100
12/12 [==============================] - 0s 2ms/step - loss: 7.1314
Epoch 87/100
12/12 [==============================] - 0s 2ms/step - loss: 8.6303
Epoch 88/100
12/12 [==============================] - 0s 3ms/step - loss: 10.0593
Epoch 89/100
12/12 [==============================] - 0s 2ms/step - loss: 8.0322
Epoch 90/100
12/12 [==============================] - 0s 2ms/step - loss: 7.5148
Epoch 91/100
12/12 [==============================] - 0s 2ms/step - loss: 7.8444
Epoch 92/100
12/12 [==============================] - 0s 2ms/step - loss: 6.0131
Epoch 93/100
12/12 [==============================] - 0s 3ms/step - loss: 6.8955
Epoch 94/100
12/12 [==============================] - 0s 2ms/step - loss: 7.4203
Epoch 95/100
12/12 [==============================] - 0s 2ms/step - loss: 6.0360
Epoch 96/100
12/12 [==============================] - 0s 2ms/step - loss: 7.0286
Epoch 97/100
12/12 [==============================] - 0s 2ms/step - loss: 5.6886
Epoch 98/100
12/12 [==============================] - 0s 2ms/step - loss: 8.6152
Epoch 99/100
12/12 [==============================] - 0s 2ms/step - loss: 6.1434
Epoch 100/100
12/12 [==============================] - 0s 2ms/step - loss: 7.1886

In [31]:
#Model evaluation 
loss = model.evaluate(X_test,y_test)

print("Mean squared Error on test data:",loss)


#
# Here we see that the Loss (mse) in the test data set is higher than the train data set hence our model overfit

5/5 [==============================] - 0s 2ms/step - loss: 17.0673
Mean squared Error on test data: 17.0672664642334